---
botToken: "Njg2MDk0MzgzOTUwNDYzMDAw.XnDUOg.x5l-Ckbp3xSKhkwPsI0TbAXE3Eg"
commandPrefix: "/"
suggestionChannelId: 689510063374860316
playerCountChannelId: 690191808625508423
sqlHostname: null
sqlPort: null
sqlUsername: null
sqlPassword: null
sqlDatabase: null
