---
########################################
### GRAND THEFT MINECART DISCORD BOT ###
###       CONFIGURATION FILE         ###
########################################


########################
# GENERAL BOT SETTINGS #
########################

# The bot token that the bot should use to log in
botToken: "insert bot token"

# The name of the bot (warning: if the name is too common, the bot will not start)
botName: "Harry"

# The webhook url

# The prefix that the bot commands should use
commandPrefix: "/"

# How long in seconds should the bot wait before removing its messages
msgDeleteTime: 30

# How long is minutes should the bot wait before deleting empty custom channels
customChannelDeleteTime: 10


###############################
# MY SQL USERS DATABASE CREDS #
###############################
usersDatabase:

  hostname: "insert host name"
  port: 3306
  username: "insert user"
  password: "insert pass"
  database: "insert db name"


##############################
# MY SQL PLAN DATABASE CREDS #
##############################
planDatabase:

  hostname: "insert host name"
  port: 3306
  username: "insert user"
  password: "insert pass"
  database: "insert db name"


##############################
# MY SQL BANS DATABASE CREDS #
##############################
bansDatabase:

  hostname: "insert host name"
  port: 3306
  username: "insert user"
  password: "insert pass"
  database: "insert db name"


#################################
# MY SQL XENFORO DATABASE CREDS #
#################################
xenDatabase:

  hostname: "insert host name"
  port: 3306
  username: "insert user"
  password: "insert pass"
  database: "insert db name"


########################
# REDIS DATABASE CREDS #
########################
redisDatabase:

  hostname: "insert host name"
  port: 3306
  username: "insert user"
  password: "insert pass"
  database: "insert db name"


#########################
#   MINESTAT SETTINGS   #
#########################
mineStatSettings:

  # The IP of the server Minestat should refresh (VPS can't ping gtm.network directly for some reason)
  serverIp: "insert ip"

  # The port of the server Minestat should refresh (Will almost always be 25565)
  serverPort: 25566

  # How often in seconds should the bot refresh the server's player count?
  refreshFrequency: 361


#########################
#   RAID MODE SETTINGS  #
#########################

raidmodeSettings:

  # The number of players that need to join in the below configured time to active raid mode
  raidModePlayers: 4

  # The time peroid over which raid mode checks players in seconds
  raidModeTime: 30

  # When raid mode is *automatically* triggered, how long after the last bot is detected should it disable (in minutes)
  raidModeDisable: 1

  # If raid mode is active, and a new player joins with in this many seconds of the previous player, punish them because they are bot (this time can't be larger then raidModeTime)
  raidModePunishTime: 15

  # How much time should we give new players to accept the rules before we kick them in minutes (forcing them to react to a msg also prevents basic bots)
  raidModeTimeToAccept: 15

  # What should we do to the players detected as bots? (Options: KICK, BAN, NOTIFY)
  raidModePunishType: "KICK"

  # What should the bot message the player on executing the punishment. You may use discord formating. Use \n for linebreaks. (Note: This only works for bans / kicks)
  raidModeMessage: "**You were kicked from the discord because you were detected being a bot! If you believe this was an error, simply rejoin at http://grandtheftmc.net/discord! **"

################################
#     RANK SETTINGS NAMES      #
################################

# The bot uses the following role ids get the role for each rank.
# Simply right click the discord role and select "copy id" to get the id.

rankSettings:
  manager: 316630771341328394
  developer: 320638685194354689
  admin: 316622289489887235
  builder: 381309906998919188
  srMod: 336611623781269506
  mod: 316621917727752193
  helper: 316660822443032576
  buildTeam: 366015517485694976
  youtuber: 536269873148461097
  supreme: 336668284399386624
  sponsor: 336668037715460097
  elite: 336666910039212046
  premium: 336666616941117442
  vip: 336666406831783937
  noRank: 691430666306453574
  unverified: 701855739324399759


###############################
#      XENFORO SETTINGS       #
###############################

# How often in seconds should the bot check if there is a new support ticket that has been received?
ticketPollingRate: 60

# The username for the dummy account used to get and take Xenforo-related information or actions like getting new tickets
dummyAccountUsername: "account username"

# The password for the dummy account used to get and take Xenforo-related information or actions like getting new tickets
dummyAccountPassword: "account password"

###############################
#      CLICKUP SETTINGS       #
###############################

# What is the API key for the click up bot account?
clickUpKey: "insert key"

# How often to refresh click up in seconds?
clickUpRefreshFrequency: 10

# How long to wait in seconds for any additional edits to be made once we detect that a bug report was updated?
clickUpWaitDuration: 45