################################################
#### Grand Theft Minecart Bot Configuration ####
####                                        ####
#### © Copyright 2020 Grand Theft Minecart, ####
####        All Rights Reserved             ####
################################################

Bot-Token: Njg2MDk0MzgzOTUwNDYzMDAw.XmU5nw.ZLzGM697T3rLRBZlrPaxa0k6TjY
